
AcceptCookiesLectra =  "//button[@id='ppms_cm_agree-to-all' and @class='ppms_cm_agree-to-all']"
LectraHomePage="//a[@class='site-logo d-block']//img[@alt='Home']"
Languages="//div[@id='block-lectra-b5-languageswitcherinterfacetext-2']//button[contains(text(),'Languages')]" 
English= "//ul[@data-block='header']/li[@hreflang='en']/a"
Fashion ="//button[normalize-space()='Fashion']"
LectraFashion= "//a[normalize-space()='Lectra & Fashion']"
FashionTitle = "//div[@class='field field--name-title field--type-string field--label-hidden field__item']//h1[text()='Fashion']"
Automotive ="//button[normalize-space()='Automotive']"
DiscoverAutomotiveJourneyButton ="//div[@class='paragraph paragraph--type--menu-mea-industrie paragraph--view-mode--menu']//a[normalize-space()='Discover the Automotive journey']"
Furniture ="//button[normalize-space()='Furniture']"
DiscoverFurniturejourneyButton ="//div[@class='paragraph paragraph--type--menu-mea-industrie paragraph--view-mode--menu']//a[normalize-space()='Discover the Furniture journey']"
AboutUsDropdown= "//button[contains(@class,'dropdown-toggle') and normalize-space(text())='About us']"
DiscoverLectra = "//div[@id='block-lectra-b5-headernavigation']//ul//a[contains(@class,'nav-link')][normalize-space()='Discover Lectra']"
DiscoverLectraPage = "//img[@alt='We light the path for you to lead the way']"
